server.port=${PORT:8080}
spring.application.name=jeu-reflexion-jee
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:}
spring.thymeleaf.cache=false
